### ISSUE TITLE
Cannot expand tokens to see more options

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/entity_token#1]
I installed this module to get more token options for a taxonomy field (e.g. `[node:field-category]`). Before this module, there was no arrow next to that token. After installing this module there's now an arrow next to this token, but I can't click on it (or rather, when I do, nothing happens). There's no console log messages for this either.

**Comment by docwilmot** [comment]
THis is weird. The collapsed items are there, you can see them in the inspector, but they wont expand. Will need a while.

**Comment by docwilmot** [comment]
@BWPanda posted this on Zulip:
> docwilmot: advice wanted please. I ported Entity Token module. But just discovered that that module did a str_replace on all field names to change underscores to dashes. On checking, it seems this was a source of contention between D7 Token and Entity Token maintainers. So now a new user of my port (maybe the first user) has complained about the token browser links not working. I've discovered this is because the browser has two copies of all field tokens, one with a name made of underscores, one with dashes, but both would have an ID made of dashes. This is the same in D7 but it caused no proble there, but messes up the JS in Backdrops Treetable implementation

> docwilmot: So this would be an opportunity to resolve an old D7 war, and just switch Entity Token to use underscores.

> docwilmot: Fixes the token browser issues (I checked)

@serundeputy replied
> Geoff St. Pierre (serundeputy)17:13
do it;

As a potential user of the module, do you think this would be an issue? I kind of agree with @serundeputy

**Comment by ghost** [comment]
I'd love that everything would be consistent! But this would mean changing all tokens from dashes to underscores... Would it be possible to automate this in an update hook?

**Comment by docwilmot** [comment]
For the sake of future sanity I'm going to change this to use underscores. Apologies to anyone whos using this already for the delay,

**Comment by docwilmot** [comment]
Resolved.
