### ISSUE TITLE
Entity Tokens throws warning if comments not enable

### ISSUE THREAD

**Issue by e0Re0R** [backdrop-contrib/entity_token#32]
Hi,
my site does not have comments enabled.
Installing (& enabling) Entity Tokens throws a warning in the status report -
"The following token types are not defined but have tokens:
    $info['types']['comment']"

This only appears if comments and Entity Tokens is are both enabled.
 
Its not killing my site or anything, more just an FYI

N

**Comment by argiepiano** [comment]
Hi @e0Re0R . Thanks for reporting. This warning is thrown by Backdrop core when a token type is not defined. The module `comment` defines the token type `comment`, so it's very strange that this is shown if comment is enabled. Can you please go to admin/modules/list and double check that comment is indeed enabled? Also try clearing the caches.

Let me know also if you are using version 2.0.1 of Entity Token.

**Comment by argiepiano** [comment]
Hi again. The title of this issue is confusing. You say there that comments is not enabled, but the text of the issue seems to indicate that it is enabled. Can you please clarify?

**Comment by argiepiano** [comment]
OK, I think I understand now - I have been able to reproduce this error by disabling and uninstalling comment. I'll check why this is happening very soon.

**Comment by argiepiano** [comment]
Hi again.  I have fixed that issue. You have a couple of choices
- You can manually patch the file `entity_token.tokens.inc` by wrapping 46 through 61 as follows:
```php
  // Tokens for type comment.
  if (module_exists('comment')) {
    $info['tokens']['comment']['subject'] = array(
      'name' => 'Subject',
      'description' => t('The subject of the comment.'),
      'entity-token' => TRUE,
    );
    $info['tokens']['comment']['status'] = array(
      'name' => 'Status',
      'description' => t('Whether the comment is published or unpublished.'),
      'entity-token' => TRUE,
    );
    $info['tokens']['comment']['comment_body'] = array(
      'name' => 'Comment',
      'description' => t('Field "comment_body". The following properties may be appended to the token: value (Text), format (Text format)'),
      'entity-token' => TRUE,
    );
  }
```

- You can download the dev version with the patch I'm about to merge
- You can wait until the next release (maybe a couple of weeks)

This warning will not cause any issues, though. 

Thanks again for reporting!!!
