### ISSUE TITLE
Entity Tokens tries to create tokens for entities that don't have properties

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_token#34]
This was reported in a [forum post](https://forum.backdropcms.org/forum/upgrading-backdrop-1220), specifically for the entity i18n_translation.

**Comment by olafgrabienski** [comment]
Confirming the fix. I had a respective warning message on the Status report on a site with the *i18n* module, and after updating to *Entity Tokens* 1.x-2.0.2 the message gone.
