### ISSUE TITLE
Tokens output the string 'Array'

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/entity_token#5]
I have a term reference field that I was using in a token with no problems: `[node:field_category]` It was outputting the term name :+1: 

Then I installed this module and it started outputting `Array` :-1:
I thought, ok, I just need to change it to be more specific (since now I can expand that token and get more information about the term properties/fields). But even after changing this to be `[node:field_category:name]`, it still outputs `Array`...

**Comment by ghost** [comment]
I need this token for my node title. But since I couldn't use my term reference field, I decided to use a decimal field instead. However it had the same problem: outputting `Array`. Tokens work fine when this module's disabled.

Same just happened on a 'Date' field too.

**Comment by robertgarrigos** [comment]
The same happens with field_image tokens. Had to disable this module to have metatag module working properly. (https://github.com/backdrop-contrib/metatag/issues/72)

**Comment by docwilmot** [comment]
This is an unfortunate consequence of switching to underscores actually. When `hook_tokens()` fetches, both core and this module return tokens for the same thing, so the `token_generate()` function gets an array with two identical values. `[node:field_category:0]` then works, but thats a sad fix. I cant figure how to do better yet though.

**Comment by argiepiano** [comment]
@docwilmot what was the reason or rationale why `entity_token` switched to low hyphens or underscores? In Drupal 7, the `token` contrib module (which made it into core in Backdrop) created tokens for fields using low hyphens, while the `entity_token` module did the same thing but with regular hyphens (see attached image). This allowed users to differentiate the functionality of the token. Therefore tokens for fields with multiple cardinality provided by `entity_token` in Drupal (like in Backdrop) could be chained with the delta (thus the 0 `[node:field_category:0]`), BUT the tokens provided by `token` for the same field produced comma separated lists. 

I'm wondering if it'd be a good idea to revert to normal hyphens in tokens provided by this module, therefore avoiding issues like the ones in this report? Thoughts?

<img width="662" alt="Screen Shot 2021-11-08 at 7 40 38 PM" src="https://user-images.githubusercontent.com/9938978/140860695-a4c73834-6f75-4076-adb1-49a9b74f75dd.png">

**Comment by argiepiano** [comment]
OK, I found the discussion on #1  about this. 

I'm wondering: people using Drupal 7 lived with these two types of tokens (those with underscores and those with dashes) for many, many years. We learned that they behaved in different ways. It seems to me that the switch to underscores for tokens provided by `entity_token` has created more problems than solutions...

**Comment by oadaeh** [comment]
Would it be possible to use [hook_tokens_alter](https://docs.backdropcms.org/api/backdrop/core%21modules%21system%21system.api.php/function/hook_tokens_alter/1) to modify the core tokens so that they have the added data provided by this module, but aren't overridden by this module?

**Comment by argiepiano** [comment]
This issue is solved in version 2.x of Entity Tokens. Version 2.x will become the default version, and will require entity_plus >=1.0.14.

If you use version 1.x of this module, https://github.com/backdrop-contrib/entity_token/issues/5#issuecomment-918436431 above is one way around this problem.
