### ISSUE TITLE
date_entity_metadata_property_info_alter() uses undefined getter and setter callbacks

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_token#6]
Lines 38 and 39 of function `date_entity_metadata_property_info_alter()` in file `entity_token.module` use two  undefined getter and setter callbacks. The callbacks `entity_metadata_field_verbatim_get` and `entity_metadata_field_verbatim_set` do not exist, and generate an error for date fields that have a `todate` setting. 

Instead of these callbacks, this function should use the callbacks provided by `entity_plus` called `entity_plus_metadata_field_verbatim_get` and `entity_plus_metadata_field_verbatim_set`  (notice the "plus")

**Comment by Wylbur** [comment]
I'm running into this issue when trying to use tokens for date fields.  Any way to resolve this?
`
Error: Call to undefined function entity_metadata_field_verbatim_get() in EntityStructureWrapper->getPropertyValue() (line 440 of /var/www/docroot/modules/entity_plus/includes/entity_plus.wrapper.inc).DismissCall to undefined function entity_metadata_field_verbatim_get()
`

**Comment by Wylbur** [comment]
I applied the changes suggested by @argiepiano and this worked perfectly.  Pull request is ready for review.

**Comment by argiepiano** [comment]
@Wylbur thank you for reporting and doing a PR. We are moving all date metadata info to Entity Plus where it belongs. Also I'm rewriting entity token as it has too many clashes with core tokens on Backdrop. We'll be releasing new versions of both entity plus and entity token soon. The fix you sent has already been added to entity plus to it's current dev version I believe.

**Comment by argiepiano** [comment]
Fixed in version 1.x by #12 . Thank you, @Wylbur ! 

Please notice that this code has been moved to entity_plus in version 2.x of Entity Tokens
