### ISSUE TITLE
Offer to maintain this project

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_token#8]
I'd like to offer my help maintaining this project. Currently it doesn't list any maintainer in the readme file. I will submit a PR adding my name as maintainer and will follow the steps outlined [here](https://docs.backdropcms.org/documentation/adopt-a-project)

**Comment by klonos** [comment]
Hello @argiepiano and thank you for volunteering to maintain this project 👍🏼  ❤️ 

It seems that it was initially ported to Backdrop by @docwilmot, but he never added himself as a maintainer. @docwilmot are you happy to hand over maintainership to @argiepiano, or co-maintain it?

**Comment by klonos** [comment]
It seems that @docwilmot is happy with this (https://backdrop.zulipchat.com/#narrow/stream/218635-Backdrop/topic/Adopting.20a.20project.20.28entity_token.29/near/261580549), so I have added you as a maintainer to the project @argiepiano ...please feel free to merge your own PR to update the README.md file 😉  ...let me know if you need help with anything.

**Comment by argiepiano** [comment]
Thank you all!
